added AudioMass, CSound IDE and Web Audio Modules
notthetup/awesome-webaudio pull request #44
Opened 2020-05-29 12:03 UTC by severak

2020-05-30 01:44 UTC, notthetup requested changes

2020-05-30 01:44 UTC, notthetup commented on readme.md
> +- [Csound IDE](https://ide.csound.com/) - web IDE for [CSound programming language](https://en.wikipedia.org/wiki/Csound)
```suggestion
- [Csound IDE](https://ide.csound.com/) - web IDE for [CSound programming language](https://en.wikipedia.org/wiki/Csound).
```

2020-05-30 01:44 UTC, notthetup commented on readme.md
> +- [Web Audio Modules](https://www.webaudiomodules.org/) - synthesizers and audio effects processors for web browsers (both API and implementations)
```suggestion
- [Web Audio Modules](https://www.webaudiomodules.org/) - synthesizers and audio effects processors for web browsers (both API and implementations).
```

2020-05-30 01:44 UTC, notthetup commented
Thank you!

2020-06-01 08:07 UTC, severak commented
OK. Grammar was fixed, you can now merge it.

2020-06-03 03:20 UTC, merged